services:
  torrenthan:
    build:
      context: .
      dockerfile: Dockerfile
    image: torrenthan:northflank
    ports:
      - "7860:7860"
    environment:
      PORT: "7860"
    restart: unless-stopped
