version: "3.8"

services:
  redis:
    image: redis:7-alpine
    container_name: aiometadata_redis
    restart: unless-stopped
    volumes:
      - ./redis:/data

  aiometa
    image: ghcr.io/cedya77/aiometalatest
    container_name: aiometadata
    restart: unless-stopped
    ports:
      - "3232:3232"
    env_file:
      - .env
    volumes:
      - .//app/addon/data
    depends_on:
      - redis
